apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nodebb.fullname" . }}
type: Opaque
stringData: 
  admin.json: |
    {
      "admin:username": {{ .Values.nodebb.admin.username | required "admin name is required" | quote }},
      "admin:email": {{ .Values.nodebb.admin.email | required "admin email is required" | quote }},
      "admin:password": {{ .Values.nodebb.admin.password | required "admin password is required" | quote }},
      "admin:password:confirm": {{ .Values.nodebb.admin.password | required "admin password is required" | quote }}
    }
  database.json: |
    {
{{- if or (eq .Values.nodebb.database "redis") (not .Values.nodebb.singleMode) }}
      "redis": {
{{- if and .Values.global.database.managed .Values.global.redis.managed }}
        "host": "{{ template "common.names.fullname" .Subcharts.redis }}-master",
{{- else }}
        "host": {{ .Values.redis.auth.host | quote }},
{{- end }}
        "port": {{ .Values.redis.auth.port | quote }},
        "password": {{ .Values.redis.auth.password | quote }},
        "database": {{ .Values.redis.auth.database | quote }}
      },
{{- end }}
{{- if eq .Values.nodebb.database "mongo" }}
      "mongo": {
{{- if and .Values.global.database.managed .Values.global.mongodb.managed }}
        "host": "{{ template "mongodb.service.nameOverride" .Subcharts.mongodb }}",
{{- else }}
        "host": {{ .Values.mongodb.auth.host | quote }},
{{- end }}
        "port": {{ .Values.mongodb.auth.port | quote }},
        "username": {{ .Values.mongodb.auth.username | quote }},
        "password": {{ .Values.mongodb.auth.password | quote }},
        "database": {{ .Values.mongodb.auth.database | quote }}
      },
{{- end }}
{{- if eq .Values.nodebb.database "postgres" }}
      "postgres": {
{{- if and .Values.global.database.managed .Values.global.postgresql.managed }}
        "host": "{{ template "postgresql.v1.primary.fullname" .Subcharts.postgresql }}",
{{- else }}
        "host": {{ .Values.postgresql.auth.host | quote }},
{{- end }}
        "port": {{ .Values.postgresql.auth.port | quote }},
        "username": {{ .Values.postgresql.auth.username | quote }},
        "password": {{ .Values.postgresql.auth.password | quote }},
        "database": {{ .Values.postgresql.auth.database | quote }}
      },
{{- end }}
      "database": {{ .Values.nodebb.database | required "database type is required" | quote }}
    }
    